# Generated by Django 5.2 on 2025-05-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('resumo', models.CharField(max_length=320)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('thumb', models.ImageField(blank=True, default='/imagens/default.png', upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('num', models.IntegerField()),
                ('data', models.DateField()),
                ('resumo', models.CharField(max_length=320)),
                ('video', models.CharField(max_length=100)),
                ('notas', models.FileField(blank=True, null=True, upload_to='notas_de_aula/')),
                ('slides', models.FileField(blank=True, null=True, upload_to='slides')),
                ('code', models.FileField(blank=True, null=True, upload_to='codigos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='ccapp.curso')),
            ],
        ),
    ]
