# Generated by Django 5.2 on 2025-06-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_remove_comentario_likes_alter_comentario_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cursos',
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField()),
                ('completed_aulas', models.ManyToManyField(blank=True, related_name='completed_by', to='ccapp.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='ccapp.curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='ccapp.student')),
            ],
            options={
                'unique_together': {('student', 'curso')},
            },
        ),
    ]
