# Generated by Django 5.2 on 2025-06-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_remove_student_cursos_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='completed_aulas',
            field=models.ManyToManyField(blank=True, related_name='completado_por', to='ccapp.aula'),
        ),
    ]
