# Generated by Django 5.2 on 2025-07-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_alter_matricula_completed_aulas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='completed_aulas',
        ),
        migrations.CreateModel(
            name='AulaCompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_completada', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.aula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_completadas', to='ccapp.matricula')),
            ],
        ),
    ]
