# Generated by Django 5.2 on 2025-07-23 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0006_remove_matricula_completed_aulas_aulacompletada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='student',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='enunciado',
            new_name='pergunta',
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='letra',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_correta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.aula')),
            ],
            options={
                'unique_together': {('aluno', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ccapp.questao')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.alternativa')),
            ],
        ),
        migrations.DeleteModel(
            name='AulaCompletada',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
