# Generated by Django 5.2 on 2025-07-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0007_remove_comentario_aula_remove_comentario_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video',
        ),
        migrations.AddField(
            model_name='aula',
            name='video_id',
            field=models.CharField(blank=True, help_text='Idealmente para um link de youtube', max_length=20),
        ),
    ]
