# Generated by Django 5.2 on 2025-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0008_remove_aula_video_aula_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='video_url',
            field=models.CharField(blank=True, help_text='Idealmente para um link de youtube', max_length=255),
        ),
    ]
