# Generated by Django 5.2 on 2025-07-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0009_remove_aula_video_id_aula_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aula',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
