# Generated by Django 5.2 on 2025-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0012_alter_curso_nome_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, default='Perfil de um usuário do CodeClass', max_length=256, null=True),
        ),
    ]
