# Generated by Django 5.2 on 2025-09-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0015_alter_comentario_aula_alter_comentario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Confirmar Conclusão da Aula', max_length=200)),
                ('tipo', models.CharField(choices=[('CHECKBOX', 'Confirmação Simples')], default='CHECKBOX', max_length=10)),
                ('enunciado', models.TextField(blank=True, default='Marque a caixa para concluir a aula', null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='ccapp.aula')),
            ],
        ),
    ]
