# Generated by Django 5.2 on 2025-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0016_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaquestao',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='respostaquestao',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='respostaquestao',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.DeleteModel(
            name='RespostaQuestao',
        ),
    ]
