# Generated by Django 5.2 on 2025-09-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0017_remove_respostaquestao_resposta_remove_questao_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='texto_atividade',
            field=models.TextField(blank=True, default='Marque a caixa para concluir a aula', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('CHECKBOX', 'Confirmação Simples')], default='CHECKBOX', max_length=10),
        ),
    ]
