# Generated by Django 5.2 on 2025-09-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0018_aula_texto_atividade_aula_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
