# Generated by Django 5.2 on 2025-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0019_delete_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoaula',
            name='resposta_atividade',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='texto_atividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('CHECKBOX', 'Confirmação Simples'), ('TEXTO', 'Resposta de Texto')], max_length=10),
        ),
    ]
